trigger:
  - master

pool:
  vmImage: 'windows-latest'

jobs:
- job: Build
  steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean install'

- job: Test
  dependsOn: Build  # Ensures the Test job runs after the Build job
  steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'test'
        options: '-Dsurefire.suiteXmlFiles=testng.xml'

- job: PublishResults
  dependsOn: Test  # Ensures the PublishResults job runs after Test
  steps:
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '**/TEST-*.xml'
        testRunTitle: 'TestNG Test Results'